---
- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb

- name: Install config file /etc/my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb
  tags: mariadb

- name: Install ~/.my.cnf
  template:
    src: home_my.cnf.j2
    dest: ~/.my.cnf
    mode: '0600'
  tags: mariadb

- name: Ensure service is started
  service:
    name: mariadb
    state: started
    enabled: yes
  tags: mariadb

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mariadb

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  tags: mariadb

- name: Remove anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags: mariadb

- name: Create the databases
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ mariadb_databases }}"
  tags: mariadb

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    encrypted: "{{ item.encrypted }}"
    state: present
  with_items: "{{ mariadb_users }}"
  tags: mariadb

- name: Grant user
  mysql_user:
   name: racktables_user
   password: "{{ racktables_user_password }}"
   state: present
   append_privs: yes
   priv: 'racktables_db.*:ALL'
  tags: mariadb  
